### ISSUE TITLE
Support for addons

### ISSUE THREAD

**Issue by jaroslav-kubicek** [test-stack/harness#10]
Various users will have various requirements. They should be able to extend our core functionality. I have following proposal:
- user will install addons via npm
- installed addons will be specified in config.cson like this:

```
testStack:
  addons:
    customReport: true
    targetProcess:
      option: 'value'
      anotherOption: 1
```
- addons will NOT be invoked by EventEmitter, but specified npm modules will be loaded and functions will be called on specified places - that will enable possibility to abort some predefied core action or change behavior based on return value
- there will be standardized list of functions, that can be called
- each addon could implement only small portion of them, if function isn't defined, nothing will be called at all
